---
- name: update software packges
  hosts: all
  become: yes
  vars:
     administrator_name: corpadmin
  tasks: 
      - name: update all
        yum:
            name: '*'
            state: latest
      - name: create user name
        user:
            name: "{{administrator_name}}"
            password: mypassword123
- name: web1 tasks
  hosts: web1
  become: yes
  tasks: 
      - name: Install nginx
        yum:
           name: nginx
           state: present
      - name: copy conf
        copy:
           src: ~/assignment-ansible/default.conf.j2
           dest: /etc/nginx/conf.d/default.conf
      - name: Start nginx if not running
        service:
           name: nginx
           enabled: yes
           state: started

- name: database1 tasks
  hosts: database1
  become: yes
  tasks:
      - name: install mysql
        yum: 
           name: mysql-server
           state: present
      - name: Start mysql if not running
        service:
           name: mysqld
           enabled: yes
           state: started
      - name: Loop to create 5 directories
        loop_control:
           loop_var: item
        file: 
           dest: /var/data/client{{ item }}
           state: directory
        with_sequence: start=1 end=5 stride=1 
